name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle 8.11.1
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.11.1'
    - name: Build with Gradle 8.11.1
      run: gradle build

    - name: Build with Gradle Wrapper
      run: |
        chmod +x ./gradlew
        ./gradlew build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
       name: JAR
       path: build/libs/*.jar
